// Generated by CoffeeScript 1.10.0
var chai, dbconnected;

chai = require("chai");

chai.should();

dbconnected = require('./collection');

describe("dbconnected()", function() {
  it("應發現證券品種", function(done) {
    return dbconnected(function(err, db) {
      var secs;
      secs = db.collection("securities");
      return secs.find().toArray(function(err, doc) {
        doc.length.should.equal('n');
        db.close;
        return done();
      });
    });
  });
  return it("應發現證券品種代碼", function(done) {
    return dbconnected(function(err, db) {
      var secs;
      secs = db.collection("securities");
      return secs.find().toArray(function(err, doc) {
        var codes, sec;
        codes = (function() {
          var i, len, results;
          results = [];
          for (i = 0, len = doc.length; i < len; i++) {
            sec = doc[i];
            results.push(sec.SecurityCode);
          }
          return results;
        })();
        (typeof codes[0]).should.equal('string');
        db.close;
        return done();
      });
    });
  });
});

//# sourceMappingURL=index.test.js.map
